// ============================================================================
// SECTOR CLASSIFICATION — used to construct our own sector indices from
// constituents (equal-weighted composite of member returns), since NSE's own
// 400+ index feed is not freely available.
//
// Coverage: the full F&O + MTF universe (~355 liquid NSE names, i.e. roughly
// Nifty-500 territory, which is where essentially all sector movement lives).
// Add a symbol to any list and it joins that sector index automatically.
// ============================================================================

export const SECTOR_MAP = {
  "Banks — Private": ["HDFCBANK","ICICIBANK","AXISBANK","KOTAKBANK","INDUSINDBK","AUBANK","BANDHANBNK","FEDERALBNK","IDFCFIRSTB","RBLBANK","YESBANK","KARURVYSYA","IDBI"],
  "Banks — PSU": ["SBIN","BANKBARODA","BANKINDIA","CANBK","INDIANB","PNB","UNIONBANK","MAHABANK"],
  "NBFC & Finance": ["BAJFINANCE","BAJAJFINSV","BAJAJHLDNG","ABCAPITAL","CHOLAFIN","SHRIRAMFIN","MUTHOOTFIN","MANAPPURAM","LICHSGFIN","PNBHOUSING","SBICARD","PFC","RECLTD","IRFC","IREDA","JIOFIN","LTF","POONAWALLA","M&MFIN","CREDITACC","FIVESTAR","IIFL","CHOLAHLDNG","SUNDARMFIN"],
  "Insurance": ["HDFCLIFE","SBILIFE","ICICIPRULI","ICICIGI","LICI","MFSL","STARHEALTH","NIACL"],
  "Capital Markets": ["BSE","MCX","CDSL","CAMS","KFINTECH","ANGELONE","MOTILALOFS","NUVAMA","360ONE","HDFCAMC","NAM-INDIA","UTIAMC","IEX","PAYTM","POLICYBZR","CRISIL"],
  "IT & Software": ["TCS","INFY","HCLTECH","WIPRO","TECHM","LTM","COFORGE","PERSISTENT","MPHASIS","KPITTECH","TATAELXSI","OFSS","NAUKRI","BSOFT","CYIENT","SONATSOFTW","ZENSARTECH","HAPPSTMNDS","FSL","TATATECH","INDIAMART","ROUTE","TEAMLEASE"],
  "Auto": ["MARUTI","M&M","TMPV","EICHERMOT","HEROMOTOCO","BAJAJ-AUTO","TVSMOTOR","ASHOKLEY","HYUNDAI","FORCEMOT","ESCORTS","OLECTRA","ZFCVINDIA"],
  "Auto Ancillaries": ["MOTHERSON","BOSCHLTD","BHARATFORG","SONACOMS","TIINDIA","UNOMINDA","EXIDEIND","ENDURANCE","MINDACORP","SCHAEFFLER","SUNDRMFAST","APOLLOTYRE","BALKRISIND","CEATLTD","TIMKEN","RKFORGE","MRF"],
  "Pharma": ["SUNPHARMA","DRREDDY","CIPLA","DIVISLAB","TORNTPHARM","LUPIN","ALKEM","ZYDUSLIFE","AUROPHARMA","GLENMARK","BIOCON","MANKIND","LAURUSLABS","IPCALAB","AJANTPHARM","NATCOPHARM","ERIS","JBCHEPHARM","GRANULES","PPLPHARMA","SUVEN","ABBOTINDIA","PFIZER","SANOFI","GLAXO","SYNGENE"],
  "Healthcare Services": ["APOLLOHOSP","MAXHEALTH","FORTIS","MEDANTA","NH","RAINBOW","ASTERDM","LALPATHLAB","METROPOLIS","VIJAYA"],
  "FMCG": ["HINDUNILVR","ITC","NESTLEIND","BRITANNIA","DABUR","GODREJCP","MARICO","TATACONSUM","COLPAL","VBL","UNITDSPR","RADICO","PATANJALI","GODFRYPHLP","UBL","EMAMILTD","JYOTHYLAB","GILLETTE","PGHH","HATSUN","KPRMILL"],
  "Retail & Consumer": ["DMART","TRENT","TITAN","ETERNAL","SWIGGY","NYKAA","KALYANKJIL","JUBLFOOD","VMM","BATAINDIA","RAYMOND","SAPPHIRE","TTKPRESTIG"],
  "Consumer Durables": ["HAVELLS","VOLTAS","CROMPTON","DIXON","AMBER","BLUESTARCO","KAYNES","PGEL","POLYCAB","SYRMA","WHIRLPOOL","VGUARD","CERA","KAJARIACER","ELGIEQUIP"],
  "Metals & Mining": ["TATASTEEL","JSWSTEEL","HINDALCO","VEDL","JINDALSTEL","SAIL","NMDC","NATIONALUM","HINDZINC","COALINDIA","APLAPOLLO","HINDCOPPER","RATNAMANI","SHYAMMETL","WELCORP","MAHSEAMLES","HEG","RHIM"],
  "Oil & Gas": ["RELIANCE","ONGC","IOC","BPCL","HINDPETRO","GAIL","OIL","PETRONET","MRPL","GUJGASLTD","IGL","MGL","ATGL","CASTROLIND"],
  "Power & Utilities": ["NTPC","POWERGRID","TATAPOWER","ADANIPOWER","ADANIGREEN","ADANIENSOL","JSWENERGY","NHPC","SJVN","SUZLON","WAAREEENER","PREMIERENE","INOXWIND","TORNTPOWER","CESC"],
  "Capital Goods": ["ABB","SIEMENS","CUMMINSIND","BHEL","CGPOWER","KEI","GVT&D","POWERINDIA","THERMAX","AIAENG","GRINDWELL","CARBORUNIV","HONAUT","SKFINDIA","KEC","APARINDS","FINCABLES","KIRLOSENG"],
  "Defence & Railways": ["HAL","BEL","BDL","MAZDOCK","COCHINSHIP","SOLARINDS","RVNL","RAILTEL","RITES","IRCTC","SWANDEF"],
  "Infra & Construction": ["LT","GMRAIRPORT","NBCC","NCC","IRB","PNCINFRA","HUDCO"],
  "Cement & Building Materials": ["ULTRACEMCO","AMBUJACEM","SHREECEM","DALBHARAT","GRASIM","ACC","RAMCOCEM","JKCEMENT","JKLAKSHMI","ASTRAL","SUPREMEIND","CENTURYPLY"],
  "Realty": ["DLF","LODHA","GODREJPROP","OBEROIRLTY","PRESTIGE","PHOENIXLTD","SOBHA"],
  "Chemicals & Fertilisers": ["PIDILITIND","SRF","PIIND","UPL","DEEPAKNTR","AARTIIND","NAVINFLUOR","VINATIORGA","FINEORG","ATUL","TATACHEM","COROMANDEL","CHAMBLFERT","EIDPARRY","BALRAMCHIN","TRIVENI","BASF","BAYERCROP","SUMICHEM","LINDEINDIA","PCBL","GODREJIND"],
  "Paints": ["ASIANPAINT","BERGEPAINT","KANSAINER"],
  "Telecom & Media": ["BHARTIARTL","IDEA","INDUSTOWER","TATACOMM","SUNTV","HFCL","TRIDENT"],
  "Logistics": ["ADANIPORTS","CONCOR","DELHIVERY","BLUEDART","GESHIP","SCI"],
  "Hotels & Travel": ["INDHOTEL","INDIGO","EIHOTEL"],
  "Textiles & Apparel": ["PAGEIND","ABFRL","WELSPUNLIV"],
  "Diversified": ["ADANIENT","SWANCORP"]
};

// symbol -> sector
export const SYM_SECTOR = (() => {
  const m = {};
  for (const [sec, list] of Object.entries(SECTOR_MAP)) for (const s of list) m[s] = sec;
  return m;
})();

export const SECTOR_NAMES = Object.keys(SECTOR_MAP);
export default SECTOR_MAP;
