// ============================================================================
// TRADING UNIVERSE — single source of truth for the whole app.
// Served to the frontend by /api/universe and imported by /api/refresh.
//
// FNO   : NSE Futures & Options stock list (derivatives-eligible).
// MTF3  : additional cash stocks your broker allows at ~1:3 MTF leverage
//         (i.e. ~33% margin). Broker lists differ — edit MTF3 to match yours.
//
// Symbols are NSE tickers without the .NS suffix; the app appends it.
// Anything Yahoo can't resolve is skipped automatically at fetch time.
// ============================================================================

export const FNO = [
  "AARTIIND","ABB","ABCAPITAL","ABFRL","ACC","ADANIENSOL","ADANIENT","ADANIGREEN",
  "ADANIPORTS","ALKEM","AMBUJACEM","ANGELONE","APLAPOLLO","APOLLOHOSP","APOLLOTYRE",
  "ASHOKLEY","ASIANPAINT","ASTRAL","ATGL","AUBANK","AUROPHARMA","AXISBANK",
  "BAJAJ-AUTO","BAJAJFINSV","BAJFINANCE","BALKRISIND","BANDHANBNK","BANKBARODA",
  "BANKINDIA","BEL","BERGEPAINT","BHARATFORG","BHARTIARTL","BHEL","BIOCON",
  "BOSCHLTD","BPCL","BRITANNIA","BSE","BSOFT","CAMS","CANBK","CDSL","CESC",
  "CGPOWER","CHAMBLFERT","CHOLAFIN","CIPLA","COALINDIA","COFORGE","COLPAL",
  "CONCOR","CROMPTON","CUMMINSIND","CYIENT","DABUR","DALBHARAT","DEEPAKNTR",
  "DELHIVERY","DIVISLAB","DIXON","DLF","DMART","DRREDDY","EICHERMOT","ESCORTS",
  "EXIDEIND","FEDERALBNK","FORTIS","GAIL","GLENMARK","GMRAIRPORT","GODREJCP",
  "GODREJPROP","GRANULES","GRASIM","HAL","HAVELLS","HCLTECH","HDFCAMC","HDFCBANK",
  "HDFCLIFE","HEROMOTOCO","HFCL","HINDALCO","HINDCOPPER","HINDPETRO","HINDUNILVR",
  "HUDCO","ICICIBANK","ICICIGI","ICICIPRULI","IDEA","IDFCFIRSTB","IEX","IGL",
  "INDHOTEL","INDIANB","INDIGO","INDUSINDBK","INDUSTOWER","INFY","IOC","IRB",
  "IRCTC","IREDA","IRFC","ITC","JINDALSTEL","JIOFIN","JSWENERGY","JSWSTEEL",
  "JUBLFOOD","KALYANKJIL","KEI","KOTAKBANK","KPITTECH","LAURUSLABS","LICHSGFIN",
  "LICI","LODHA","LT","LTF","LUPIN","M&M","M&MFIN","MANAPPURAM","MARICO",
  "MARUTI","MAXHEALTH","MCX","METROPOLIS","MFSL","MGL","MOTHERSON","MPHASIS",
  "MRF","MUTHOOTFIN","NATIONALUM","NAUKRI","NBCC","NCC","NESTLEIND","NHPC",
  "NMDC","NTPC","NYKAA","OBEROIRLTY","OFSS","OIL","ONGC","PAGEIND","PAYTM",
  "PERSISTENT","PETRONET","PFC","PIDILITIND","PIIND","PNB","PNBHOUSING",
  "POLICYBZR","POLYCAB","POONAWALLA","POWERGRID","PRESTIGE","RAMCOCEM","RBLBANK",
  "RECLTD","RELIANCE","SAIL","SBICARD","SBILIFE","SBIN","SHREECEM","SHRIRAMFIN",
  "SIEMENS","SJVN","SOLARINDS","SONACOMS","SRF","SUNPHARMA","SUNTV","SUPREMEIND",
  "SYNGENE","TATACHEM","TATACOMM","TATACONSUM","TATAELXSI","TATAPOWER",
  "TATASTEEL","TATATECH","TCS","TECHM","TIINDIA","TITAN","TMPV","TORNTPHARM",
  "TORNTPOWER","TRENT","TVSMOTOR","UBL","ULTRACEMCO","UNIONBANK","UNITDSPR","UPL",
  "VBL","VEDL","VOLTAS","WIPRO","YESBANK","ETERNAL","ZYDUSLIFE"
];

// Liquid non-F&O large/midcaps commonly available at ~1:3 MTF margin.
// Verify against your own broker's MTF list and edit freely.
export const MTF3 = [
  "ABBOTINDIA","ADANIPOWER","AIAENG","AJANTPHARM","APARINDS","ASTERDM","ATUL",
  "BAJAJHLDNG","BALRAMCHIN","BASF","BATAINDIA","BAYERCROP","BLUEDART","BLUESTARCO",
  "CARBORUNIV","CASTROLIND","CEATLTD","CENTURYPLY","CERA","CHOLAHLDNG","COCHINSHIP",
  "COROMANDEL","CREDITACC","CRISIL","EIDPARRY","EIHOTEL","ELGIEQUIP","EMAMILTD",
  "ENDURANCE","ERIS","FINCABLES","FINEORG","FIVESTAR","FSL","GESHIP","GILLETTE",
  "GLAXO","GODFRYPHLP","GODREJIND","GRINDWELL","GUJGASLTD","HAPPSTMNDS","HATSUN",
  "HEG","HONAUT","IDBI","IIFL","INDIAMART","INOXWIND","IPCALAB","JBCHEPHARM",
  "JKCEMENT","JKLAKSHMI","JYOTHYLAB","KAJARIACER","KANSAINER","KARURVYSYA",
  "KEC","KFINTECH","KIRLOSENG","KPRMILL","LALPATHLAB","LINDEINDIA","MAHABANK",
  "MAHSEAMLES","MEDANTA","MINDACORP","MRPL","NAM-INDIA","NATCOPHARM","NAVINFLUOR",
  "NH","NIACL","NUVAMA","OLECTRA","PCBL","PFIZER","PGHH","PHOENIXLTD","PNCINFRA",
  "PPLPHARMA","RADICO","RAILTEL","RAINBOW","RATNAMANI","RAYMOND","RHIM","RITES",
  "RKFORGE","ROUTE","RVNL","SANOFI","SAPPHIRE","SCHAEFFLER","SCI","SHYAMMETL",
  "SKFINDIA","SOBHA","SONATSOFTW","STARHEALTH","SUMICHEM","SUNDARMFIN","SUNDRMFAST",
  "SUVEN","SWANCORP","SWANDEF","SYRMA","TEAMLEASE","THERMAX","TIMKEN","TRIDENT",
  "TRIVENI","TTKPRESTIG","UTIAMC","VGUARD","VIJAYA","VINATIORGA","WELCORP",
  "WELSPUNLIV","WHIRLPOOL","ZENSARTECH","ZFCVINDIA"
];

export const UNIVERSE = [...new Set([...FNO, ...MTF3])];
export default UNIVERSE;
